# file: roles/compute-node/defaults/main.yml
---

nanoconfig_service_endpoint: tcp://nanoconfig.service.{{ watcher_dc_domain }}:{{ nanoconfig_server_reply_port }}
nanoconfig_update_endpoint: tcp://nanoconfig.service.{{ watcher_dc_domain }}:{{ nanoconfig_server_update_port }}
publisher_endpoint: watcher-metering-publisher.service.{{ watcher_dc_domain }}:{{ publisher_port }}

watcher_metering_config_dir: /etc/watcher-metering
watcher_metering_agent_config_file: "{{ watcher_metering_config_dir }}/agent.conf"
watcher_metering_service_file: /etc/init.d/watcher-metering-agent

watcher_metering_pdu_servers:
  Brest: 10.50.0.151
  Lannion: 10.50.0.152

watcher_metering_pdu_mapping:
  Brest: "[bdev-indeedsrv007:1,bdev-indeedsrv008:2]"
  Lannion: "[ldev-indeedsrv005:1,ldev-indeedsrv006:2]"
