# file: roles/compute-node/defaults/main.yml
---

#nanoconfig_service_endpoint: tcp://nanoconfig.service.{{ watcher_dc_domain }}:{{ nanoconfig_server_reply_port }}
#nanoconfig_update_endpoint: tcp://nanoconfig.service.{{ watcher_dc_domain }}:{{ nanoconfig_server_update_port }}
#publisher_endpoint: watcher-metering-publisher.service.{{ watcher_dc_domain }}:{{ publisher_port }}

watcher_metering_config_dir: /etc/watcher-metering
watcher_metering_drivers_config_file: "{{ watcher_metering_config_dir }}/drivers.conf"

driver_names:
  - cpu_count
  - cpu_user
  - cpu_idle
  - disk_used
  - memory_used
  # - instance_cpu_used
  # - disk_total
  # - disk_free
  # - memory_total
  # - memory_free
  # - swap_total
  # - swap_used
  # - swap_free
  # - energy_active_energy
  # - energy_active_power
  # - energy_rms_current
  # - energy_rms_voltage
  # - energy_apparent_power
  # - energy_power_factor
  # - energy_on_off
  # - energy_frequency_puller

watcher_metering_pdu_servers:
  Brest: 10.50.0.151
  Lannion: 10.50.0.152

watcher_metering_pdu_mapping:
  Brest: "[bdev-indeedsrv007:1,bdev-indeedsrv008:2]"
  Lannion: "[ldev-indeedsrv005:1,ldev-indeedsrv006:2]"
